version: "3.7"

networks:
  default:
    name: mosquitto-default

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: $COMPOSE_PROJECT_NAME
    restart: unless-stopped
    ports:
    - 1883:1883
    - 9001:9001
    volumes:
      - ./config:/mosquitto/config/:rw